package com.example.casey.databindexample.models;

import android.databinding.BaseObservable;
import android.databinding.Bindable;

// Autogenerated with ids for fields marked @Bindable
import com.example.casey.databindexample.BR;

public class Boat extends BaseObservable {
    private String name;
    private int length;
    private String manufacturer;

    @Bindable
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        notifyPropertyChanged(BR.name);
    }

    @Bindable
    public int getLength() {
        return length;
    }

    public void setLength(int length) {
        this.length = length;
        notifyPropertyChanged(BR.length);
    }

    @Bindable
    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
        notifyPropertyChanged(BR.manufacturer);
    }

    public Boat(String name, int length, String manufacturer) {
        this.name = name;
        this.length = length;
        this.manufacturer = manufacturer;
    }
}
